// <auto-generated />
using BdMarketWebApp.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BdMarketWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190813140141_CreateDesignationTable")]
    partial class CreateDesignationTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BdMarketWebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionBy");

                    b.Property<string>("ActionName");

                    b.Property<string>("ActionTime");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BdMarketWebApp.Models.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionBy");

                    b.Property<string>("ActionDone");

                    b.Property<string>("ActionTime");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("BdMarketWebApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionBy");

                    b.Property<string>("ActionDone");

                    b.Property<string>("ActionTime");

                    b.Property<decimal>("BasePrice");

                    b.Property<int>("CategoryId");

                    b.Property<string>("EntryDate")
                        .IsRequired();

                    b.Property<int>("EntryMonth");

                    b.Property<int>("EntryYear");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("ProductDescription");

                    b.Property<string>("ProductTitle")
                        .IsRequired();

                    b.Property<decimal>("Profit");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("SellPrice");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BdMarketWebApp.Models.Product", b =>
                {
                    b.HasOne("BdMarketWebApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
